services:

  front:
    image: "icws24submission/front_v5"
    container_name: soy_front_v5
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - "3001:8000"
    env_file:
      - variables.env
    networks:
      - appnet

  postgres:
    container_name: postgres
    image: icws24submission/postgres_icws24
    shm_size: 1g
    security_opt:
      - no-new-privileges:true
    restart: always
    env_file:
      - variables.env
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  gateway:
    container_name: gateway
    build:
      context: ./gateway-http
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - ms-exercise
      - ms-other
    ports:
      - "5001:8080"
    networks:
      - appnet
    env_file:
      - variables.env

  ms-exercise:
    container_name: ms-exercise
    build:
      context: ./exercise-http
    security_opt:
      - no-new-privileges:true
    restart: always
    networks:
      - appnet
    env_file:
      - variables.env
    deploy:
      replicas: 1

  ms-other:
    container_name: ms-other
    build:
      context: ./other-http
    security_opt:
      - no-new-privileges:true
    restart: always
    networks:
      - appnet
    env_file:
      - variables.env
    deploy:
      replicas: 1

networks:
  appnet:
    driver: bridge

volumes:
  pgdata: